### ISSUE TITLE
Switch to serverless

### ISSUE THREAD

**Issue by amureki** [Thermondo/stanley#10]
Using one of those:
 - https://github.com/Miserlou/Zappa
 - https://github.com/aws/chalice

**Comment by amureki** [comment]
@codingjoe we still can use Redis from Heroku for lambda function in AWS, for example, but do you know how can we manage to schedule commands there?

**Comment by codingjoe** [comment]
@amureki I think this is an overkill. You would need to use a different storage solution. Honestly it's easier to keep as is. A hobby dyno doesn't cost the world.
